disallowed-methods = [
    # Use fs_errr functions, so the filename is available in the error message
    { path = "std::fs::canonicalize", replacement = "fs_err::canonicalize" },
    { path = "std::fs::copy", replacement = "fs_err::copy" },
    { path = "std::fs::create_dir", replacement = "fs_err::create_dir" },
    { path = "std::fs::create_dir_all", replacement = "fs_err::create_dir_all" },
    { path = "std::fs::exists", replacement = "fs_err::exists" },
    { path = "std::fs::hard_link", replacement = "fs_err::hard_link" },
    { path = "std::fs::read", replacement = "fs_err::read" },
    { path = "std::fs::read_dir", replacement = "fs_err::read_dir" },
    { path = "std::fs::read_link", replacement = "fs_err::read_link" },
    { path = "std::fs::read_to_string", replacement = "fs_err::read_to_string" },
    { path = "std::fs::remove_dir", replacement = "fs_err::remove_dir" },
    { path = "std::fs::remove_dir_all", replacement = "fs_err::remove_dir_all" },
    { path = "std::fs::remove_file", replacement = "fs_err::remove_file" },
    { path = "std::fs::rename", replacement = "fs_err::rename" },
    { path = "std::fs::set_permissions", replacement = "fs_err::set_permissions" },
    { path = "std::fs::soft_link", replacement = "fs_err::soft_link" },
    { path = "std::fs::write", replacement = "fs_err::write" },

    { path = "std::path::Path::canonicalize", reason = "Use fs_err alternative" },
    { path = "std::path::Path::read_link", reason = "Use fs_err alternative" },
    { path = "std::path::Path::read_dir", reason = "Use fs_err alternative" },

    { path = "std::fs::metadata", replacement = "fs_err::symlink_metadata" },
    { path = "std::fs::symlink_metadata", replacement = "fs_err::symlink_metadata" },
    { path = "std::path::Path::metadata", replacement = "fs_err::symlink_metadata" },
    { path = "std::path::Path::symlink_metadata", replacement = "fs_err::symlink_metadata" },

    { path = "std::path::Path::try_exists", reason = "use utils helper" },

    { path = "fs_err::metadata", replacement = "fs_err::symlink_metadata" },
    { path = "fs_err::PathExt::fs_err_metadata", replacement = "fs_err::symlink_metadata" },
]
